import type { Pricing } from '@/types'

/**
 * Hardcoded pricing used when Sanity has no `pricing` documents yet. Shared by
 * the /pricing page and the per-product ProductPricing section so the two never
 * drift.
 */
export const fallbackPricing: Pricing[] = [
  {
    _id: 'both-pricing',
    price: 'Free + 2.5%',
    priceSuffix: 'hotels free · 2.5% per ticket',
    tagline: 'The complete event commerce suite.',
    highlighted: true,
    includes: [
      'Everything in Hotels for Events',
      'Everything in Ticketing for Events',
      'Single dashboard for hotels and tickets',
      'One team, one setup, one point of contact',
      'Full customer service handled by Hoperfy',
      'Priority support',
    ],
    cta: 'Get the full suite',
    product: { title: 'Hotels + Ticketing', slug: 'both', tagline: 'Complete event commerce' },
  },
  {
    _id: 'ticketing-pricing',
    price: '2.5%',
    priceSuffix: 'per ticket sold',
    tagline: 'Simple fees. No surprises. Free for free events.',
    highlighted: false,
    includes: [
      'Free for free events — no fees whatsoever',
      '2% platform fee per paid ticket (Full Suite) or 2.5% separately',
      '1.5%–2.9% payment processing fee (Stripe)',
      'Use our payment gateway or connect your own',
      'Multi-channel ticket sales',
      'Dynamic pricing and capacity controls',
      'Unified attendee data across all channels',
      'Instant payouts as tickets sell',
      'QR check-in and access management',
      'Scanner app for door management',
      'Announcements to all attendees',
      'Multiple ticket types per event',
      'Invoicing and receipt generation',
      'Managed setup by our team',
    ],
    cta: 'Start selling tickets',
    product: {
      title: 'Ticketing for Events',
      slug: 'ticketing-for-events',
      tagline: 'Multi-platform ticket sales',
      fullFeatures: [
        'Free for free events — no fees whatsoever',
        '2% platform fee per paid ticket (Full Suite) or 2.5% separately',
        '1.5%–2.9% payment processing fee (Stripe)',
        'Use our payment gateway or connect your own',
        'Multi-channel ticket sales from one dashboard',
        'Sell from your own site and partner platforms',
        'Dynamic pricing and capacity controls',
        'Early bird and tiered pricing',
        'Multiple ticket types per event',
        'Unified attendee data across all channels',
        'Instant payouts as tickets sell',
        'QR check-in and access management',
        'Scanner app for door management',
        'Announcements to all attendees',
        'Invoicing and receipt generation',
        'Real-time sales dashboard',
        'Managed setup by our team',
        'Live in 5 minutes',
      ],
    },
  },
  {
    _id: 'hotels-pricing',
    price: 'Free',
    priceSuffix: 'forever',
    tagline: 'We set it up. You keep the revenue.',
    highlighted: false,
    includes: [
      'White-label hotel booking page',
      'Negotiated rate management',
      'Real-time room block tracking',
      'Automated rooming list exports',
      'Managed setup by our team',
      'Unlimited bookings',
      'Full customer service handled by Hoperfy',
      'Cancellations, changes, and payments managed for you',
    ],
    cta: 'Get started free',
    product: {
      title: 'Hotels for Events',
      slug: 'hotels-for-events',
      tagline: 'White-label hotel booking',
      fullFeatures: [
        'White-label hotel booking page',
        'Your branding, your domain',
        'Negotiated rate management',
        'Real-time room block tracking',
        'Group block pickup reporting',
        'Automated rooming list exports',
        'Unlimited bookings',
        'Full customer service by Hoperfy',
        'Cancellations and changes handled for you',
        'Payments and refunds managed for you',
        'Managed setup by our team',
        'Live within 5 minutes',
      ],
    },
  },
]

export const fallbackPricingBySlug: Record<string, Pricing> = {
  'hotels-for-events': fallbackPricing.find((p) => p.product.slug === 'hotels-for-events')!,
  'ticketing-for-events': fallbackPricing.find((p) => p.product.slug === 'ticketing-for-events')!,
}
